### ISSUE TITLE
[BE] Add : 좋아요 기능

### ISSUE THREAD

**Issue by bamjun** [OZ-Coding-School/oz_02_collabo-006#24]
### Issue
- Group: `BE` 
- Type: 'Add`
- 좋아요 눌렀을때 pots 테이블에 좋아요 카운트필드만 만듬.
- likes테이블 따로 만들어서 유저가 어느 게시물을 좋아요 눌렀는지 확인해야함.

### TO-DO
1. Like 테이블 생성하기
2. posts urls.py에 like url 추가
3. posts serilaizers.py에 좋아요 시리얼라이즈 생성
4. posts views.py에 좋아요 코드 작성 (좋아요 생성/취소, 좋아요 개별 조회/리스트 조회)

**Comment by joowhi** [comment]
PostLike 클래스 생성
- get 함수
  - get_status가 "True"(str)이면 게시물에 사용자가 좋아요 했는지 조회 -> post_id랑 get_status로 테스트
  - get_status가 "True"가 아니면 사용자가 좋아요한 게시물 리스트 조회
- post 함수
  - 현재 좋아요가 되어 있으면 좋아요 취소 -> post_id로 테스트
  - 현재 좋아요가 안 되어 있으면 좋아요 생성
