### ISSUE TITLE
[BE] FEAT: 게시글 기능 구현

### ISSUE THREAD

**Issue by joowhi** [OZ-Coding-School/oz_02_collabo-006#5]
### Issue
- Group: `BE` 
- Type: `feature`

### TO-DO
1. POST 테이블 생성
2. 전체 게시글 조회 API
3. 게시글 생성 API
4. 특정 게시글 조회 API
5. 게시글 수정 API
6. 게시글 삭제 API
7. 특정 유저의 게시글 조회 API

8. 게시글 기능 Postman 테스트

**Comment by joowhi** [comment]
- 로그인 된 사용자 확인하기
- 특정 사용자의 게시글 조회하기

**Comment by joowhi** [comment]
- 특정 사용자의 게시글 불러오기(로그인된 사람이 아닌 user_id로)
- 게시글 상세 조회할 때 로그인한 사람만 가능하게 하기
- 로그인한 사람만 게시글 생성 가능 
- 글 올린 당사자만 해당 게시글 수정
- 글 올린 당사자만 해당 게시글 삭제

**Comment by joowhi** [comment]
- Post / Media 테이블 관계 (1:N / N:M) => 생각해보기
- Image -> NCP Object Storage -> URL 반환된 거를 Medias에 저장 -> Post에 media_id 저장 => 후에 생각

**Comment by bamjun** [comment]
# 추가로 해야 할 사항. 
- 좋아요 기능 추가하기 
- 게시글에 대한 좋아요 기능 추가하기

![Image](https://github.com/OZ-Coding-School/oz_02_collabo-006/assets/21354840/fb16b712-62c9-436c-a398-eb4cf2fd1814)

**Comment by bamjun** [comment]
- 게시물 생성시 해시태그 리스트로 받기.

작성하는 api
전체 조회 api

**Comment by bamjun** [comment]
전체조회할때 최신순으로 24개만 조회 - 카테고리 필드에 new 로 api 받을때 최신순 24개 보내기

**Comment by bamjun** [comment]
이미지 불러오는 부분 request.FILES-> request.data 문자열 인코딩으로 변경

**Comment by bamjun** [comment]
- 게시글 생성하는 부분 완료
  - 미디어 올리기, 해쉬태그, 해쉬테그 중간 테이블에 데이터 생성, 미디어 url 저장

**Comment by joowhi** [comment]
- 전체 게시물 조회 완료(visible=True 인 것만)
  - 게시물 'new'를 기본으로 최신순으로 24개씩 데이터 불러오기

- 게시물 생성 완료
  - 미디어, 해시태그 저장

- 게시물 수정 진행 중
  - 게시물 수정 시, 해시태그와 미디어 처리

**Comment by joowhi** [comment]
- 게시물 생성 또는 수정 시 발생하는 응답 렌더링 에러 Fix
  - image_upload 함수 내 이미지 생성 성공 여부 return 값 Response 대신 빈 리스트로 반환하도록 변경
  - 반환값 변경 후 테스트 성공

- 게시물 수정 시, 해시태그와 미디어 처리 코드 작성
  - 해시태스 Postman 테스트 완료
  - 미디어 테스트 필요    

- 좋아요 기능을 위한 테이블 추가

**Comment by joowhi** [comment]
게시글 작성할 때, 로그인이 되어 있어도 로그인 하라는 창이 계속 뜸
permission_classes 주석 처리하면 진행됨

- CustomJWTAuthentication 작성 -> 아직 해결 안 되어서 디버깅 진행 중

**Comment by joowhi** [comment]
게시글 삭제 시, S3 파일도 함께 삭제하기 - 완료

**Comment by joowhi** [comment]
게시글 수정 시 이미지를 없애는 경우, S3파일도 삭제되도록 수정
